version: "3"
services:
  web_scraper:
    build:
      context: .
      dockerfile: ./services/web_scraper/Dockerfile
    volumes:
      - ./services/web_scraper:/app
      - ./shared:/app/shared
    ports:
      - "8000:8000"
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      QDRANT_HOST: ${QDRANT_HOST}
      QDRANT_PORT: ${QDRANT_PORT}
      SERVICE_HOST: ${SERVICE_HOST}
      URL_INDEXER_SERVICE_PORT: ${URL_INDEXER_SERVICE_PORT}
      INDEX_COLLECTION_NAME: ${INDEX_COLLECTION_NAME}
