services:
  web_scraper:
    build: ./services/web_scraper
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - QDRANT_HOST=${QDRANT_HOST}
      - QDRANT_PORT=${QDRANT_PORT}
      - SERVICE_HOST=${SERVICE_HOST}
      - URL_INDEXER_SERVICE_PORT=${URL_INDEXER_SERVICE_PORT}
      - INDEX_COLLECTION_NAME=${INDEX_COLLECTION_NAME}
    volumes:
      - ./services/web_scraper:/app
    ports:
      - "8000:80"
